Jorwoods/quota tiers allow null
tableau/server-client-python pull request #1015
Opened 2022-03-28 18:28 UTC by jorwoods

Allow setting `site.user_quota` equal to None if license levels are set.

2022-03-29 00:21 UTC, jacalata requested changes
Here's a test that passes without your change: can you add it and update?
    def test_null_site_quota(self) -> None:
        test_site = TSC.SiteItem('testname', 'testcontenturl', tier_explorer_capacity=1, user_quota=None)
        assert test_site.tier_explorer_capacity == 1
        with self.assertRaises(ValueError):
            test_site.user_quota = 1
        test_site.tier_explorer_capacity = None
        test_site.user_quota = 1

2022-03-29 00:21 UTC, jacalata commented on tableauserverclient/models/site_item.py
> +        if value is not None and any(
seems kind of odd that the only way to do this is to go through a step where both user quota and site capacity are None.  Maybe a helper method like replace_capacity_with_quota(user_quota=) and vice versa would make this cleaner to do?

2022-03-29 03:31 UTC, jorwoods commented
I also modified the existing `test_update` for sites to fail appropriately if the fix is not in place. Added a new test for the new override method. Added the test proposed by @jacalata to exhibit failures when setting user_quota directly to some non-null value, but work when `None`.

2022-03-30 00:25 UTC, jacalata approved these changes

2022-03-30 00:25 UTC, merged

2022-03-30 00:25 UTC, jacalata commented
thanks!