Solution for issue number #1033
tableau/server-client-python pull request #1044
Opened 2022-05-26 13:59 UTC by amar-kumar-yadav

Tableau 2021.4 has introduced new set of permissions which are as follows:
Workbooks
  • Run Explain Data
  • Create/Refresh Metrics
Data Sources
  • Save As
  • Move
Ask Data Lenses (all new)
  • View
  • Overwrite
  • Move
  • Delete
  • Set Permissions

These permissions are missing in the current wrapper class.
I have added these permissions in the Model and also created a new populate permission method for Lense permissions.

2022-05-27 17:46 UTC, jacalata commented
Thanks for the contribution! I have a couple minor requests, then once you've signed the CLA we can merge it. 
- please run "black --check --line-length 120 tableauserverclient samples test" to auto-fix the formatting
- could you update the spelling of "lense" to "lens" everywhere?

The default lens permission is based on the default workbook permission for a project. Would it be better to use one method "update/delete_default_workbook_and_lens_permissions" so people realize they're editing both?

otherwise looks good and will make a few people very happy :)

2022-05-27 17:47 UTC, jacalata requested changes
please run "black --check --line-length 120 tableauserverclient samples test" to auto-fix the formatting
could you update the spelling of "lense" to "lens" everywhere?

2022-06-01 06:55 UTC, amar-kumar-yadav commented
Hi @jacalata , it would be better if we keep both the methods "update/delete_default_workbook_and_lens_permissions" separate. I have kept the spelling as "lense" as the API call contains "lense" and tableau server also says "lense", so would it be better if we keep the consistency.

2022-06-01 08:38 UTC, jacalata commented
No, the word is "lens". The plural is "lenses". See e.g this page for examples: https://help.tableau.com/current/online/en-us/ask_data_lenses.htm#create-or-configure-a-lens-page-on-your-tableau-site

2022-06-01 11:16 UTC, amar-kumar-yadav commented
Hi @jacalata , i have updated the word Lense to Lens. Please let me know the next steps.

2022-06-03 04:16 UTC, jacalata commented
I don't know why the checks failed on this branch, so I created a new branch and merged it in from there; https://github.com/tableau/server-client-python/pull/1053

2022-06-03 04:16 UTC, closed without merging