Site id term refactor
tableau/server-client-python pull request #500
Opened 2019-09-12 22:00 UTC by dzucker-tab

Rationalizing and clarifying uses of "site-id" and related terms.

2021-04-21 21:13 UTC, jacalata commented on docs/api-ref.md
> +`site_id` | This corresponds to the `contentUrl` attribute in the Tableau REST API. It is the portion of the URL that follows the `/site/` in the URL. For example, "MarketingTeam" is the `site_id` in
can we change this from 'site_id' to site_url_id or something? Then all the other uses of id should be luids.

2021-11-09 07:34 UTC, jacalata requested changes

2021-11-09 07:34 UTC, jacalata commented on docs/api-ref.md
> +tableau_auth = TSC.TableauAuth('username', 'password', 'site-id')
can you add back the keywords here?

2021-11-09 07:34 UTC, jacalata commented on docs/api-ref.md
> +sites.get_by_id(site_luid)
Agreed, should just be site_id again

2021-11-09 07:34 UTC, jacalata commented on docs/api-ref.md
> +sites.get_by_id(site_luid)
Also on line 2264 below, 2402, 2415, 2424,
perhaps we could add an example value here, e.g 3d512018-64c4-4b66-a1fa-1c83710e323c

2021-11-09 07:34 UTC, jacalata commented on docs/api-ref.md
> +tableau_auth = TSC.TableauAuth('username', 'password', 'site-id')
also line 3497, 3609

2021-11-09 07:34 UTC, jacalata commented on docs/index.md
> +tableau_auth = TSC.TableauAuth('username', 'password', 'site-id')
and this

2024-02-15 00:56 UTC, bcantoni commented
This one hasn't been touched in years - closing.

2024-02-15 00:56 UTC, closed without merging