Tasks Documentation
tableau/server-client-python pull request #525
Opened 2019-11-11 20:47 UTC by martinbpeters

2020-09-24 08:02 UTC, nnevalainen commented
What's the status of this PR? Tasks were introduced in [TSC v0.4](https://github.com/tableau/server-client-python/releases/tag/v0.4) by #159

2020-09-24 23:00 UTC, bcantoni commented
@nnevalainen thanks for the reminder ping on this one. The changes look good to me; let me find one more pair of eyes to check.

2020-09-24 23:00 UTC, bcantoni approved these changes

2020-09-24 23:04 UTC, bcantoni requested changes
Updating my review with just a couple minor changes needed.

2020-09-24 23:04 UTC, bcantoni commented on docs/api-ref.md
> +`task_type` | Type of extract task - full or incremental refresh.
Suggest reordering these to be in the order shown in TaskItem class above, so id, task_type, ...).

2020-09-24 23:04 UTC, bcantoni commented on docs/api-ref.md
> +`req_option` |  (Optional) You can pass the method a request object that contains additional parameters to filter the request.
This should be req_options plural to match

2020-09-28 06:19 UTC, nnevalainen commented
Thanks for the prompt reply. Are you @martinbpeters still planning to work on this? If not, how do we want to proceed?  I, for one, can perform the required changes if _allow edits from maintainers_  is checked and I'm granted the necessary permissions.

2021-04-05 18:31 UTC, merged

2021-04-05 19:00 UTC, bcantoni commented
@nnevalainen FYI: to wrap this one up, I've merged @martinbpeters original PR and then in a separate commit added my suggested changes from the review. We should be all set here.