Fetch project owner on get
tableau/server-client-python pull request #784
Opened 2021-01-26 17:18 UTC by jorwoods

Adds `owner_id` to `ProjectItem` and populates it via the `projects.get` endpoint. Adds stubs for updating owner via create/update calls, but leaves them commented out pending server-side enhancement.

2021-01-27 17:56 UTC, t8y8 commented
I think grabbing owner and populating it is great, the NotImplemented exception is fine but I'm not a fan of the comments hanging out in the code.

Would you be willing to nix the comments but keep the rest :)

2021-01-27 18:19 UTC, jorwoods commented
I can understand not liking the commented code there. I did it with the idea of referencing what needs to be enabled once the issue is resolved, but removed it.

2021-01-27 18:24 UTC, t8y8 requested changes

2021-01-27 18:24 UTC, t8y8 commented on tableauserverclient/models/project_item.py
> +        # self.owner_id = owner_id
Missed one :)

2021-01-27 18:28 UTC, jorwoods commented on tableauserverclient/models/project_item.py
> +        # self.owner_id = owner_id
Pushed patch

2021-01-27 18:28 UTC, t8y8 approved these changes
🚀

2021-02-01 19:15 UTC, merged

2021-02-01 22:44 UTC, shinchris commented
Thanks @jorwoods!