Doc updates 2012-03
tableau/server-client-python pull request #818
Opened 2021-03-09 16:04 UTC by bcantoni

Other than a few spelling and minor fixes, the main change here is showing the available user roles in a more clear way.

2021-03-12 18:13 UTC, shinchris requested changes

2021-03-12 18:13 UTC, shinchris commented on docs/api-ref.md
> +`site_role` |  The role the user has on the site. This attribute is required with you are creating a `UserItem` instance. See *User Roles* below for details.
While you're changing this, can you change "... required with" to "... required if"?

2021-03-12 18:13 UTC, shinchris commented on docs/api-ref.md
> +For REST API 3.0 and later:
I'm not sure where this list came from in the first place, but some of them look invalid.

Looking through rest api docs, here are the lists I found:
[3.0+](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_usersgroups.htm#add_user_to_site) - Creator, Explorer, ExplorerCanPublish, SiteAdministratorExplorer, SiteAdministratorCreator, Unlicensed, or Viewer

[<2.8](https://help.tableau.com/v2018.2/api/rest_api/en-us/REST/rest_api_ref.htm#Add_User_to_Site) - Creator, Explorer, ExplorerCanPublish, ReadOnly, SiteAdministratorExplorer, SiteAdministratorCreator, Unlicensed, or Viewer

3.0 is no longer supported by Tableau, but I think we can still leave the second list.

2021-04-21 20:30 UTC, bcantoni commented
This one is still on my queue to update to address Chris comments.

2021-04-23 21:26 UTC, bcantoni commented
@shinchris this is ready for another review - I addressed your comments and made one more change to add API 3.11 to the table.

2021-05-12 20:07 UTC, shinchris approved these changes

2021-05-12 20:31 UTC, merged