Document the `metadata.query` method
tableau/server-client-python pull request #896
Opened 2021-09-18 23:05 UTC by vogelsgesang

2021-09-20 21:17 UTC, t8y8 requested changes
Minor changes, but thanks for getting it started!

Docs folks should probably take a look too.

2021-09-20 21:17 UTC, t8y8 commented on docs/api-ref.md
> +The Metadata methods are based upon the [Metadata API](https://help.tableau.com/current/api/metadata_api/en-us/index.html) REST methods.
They aren't really REST methods.

I would say something like "The Metadata methods call the Metadata API, which is a GraphQL interface" or something similar

2021-09-20 21:17 UTC, t8y8 commented on docs/api-ref.md
> +The query results as a structure of `dict`s and `list`s
The query results are json interpreted by the `json` package into dicts and lists, to be a little more explicit?

2021-09-21 10:22 UTC, vogelsgesang commented
@t8y8 I addressed your issues in the new commit. Please double-check and let me know if there is anything else I should change

2021-09-21 18:28 UTC, t8y8 approved these changes
🚀

2021-09-23 01:11 UTC, merged

2021-09-23 01:11 UTC, bcantoni commented
Thanks @vogelsgesang for the addition; merged.